import React from 'react';
import { AlertTriangle, Info, Shield } from 'lucide-react';

interface LegalDisclaimerProps {
  variant?: 'banner' | 'modal' | 'inline';
  showIcon?: boolean;
  className?: string;
}

export const LegalDisclaimer: React.FC<LegalDisclaimerProps> = ({
  variant = 'banner',
  showIcon = true,
  className = ''
}) => {
  const disclaimerContent = (
    <div className="flex items-start gap-3">
      {showIcon && (
        <AlertTriangle className="h-5 w-5 text-amber-500 flex-shrink-0 mt-0.5" />
      )}
      <div className="text-sm">
        <p className="font-medium text-gray-900 dark:text-gray-100 mb-1">
          AI-Generated Analysis Disclaimer
        </p>
        <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
          This analysis is generated by artificial intelligence and is provided for informational purposes only. 
          It does not constitute legal advice, patent counsel, or professional opinion. The accuracy, completeness, 
          and reliability of AI-generated content cannot be guaranteed. Always consult with qualified legal professionals 
          for patent-related decisions and legal matters.
        </p>
      </div>
    </div>
  );

  if (variant === 'modal') {
    return (
      <div className={`bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6 shadow-lg ${className}`}>
        {disclaimerContent}
      </div>
    );
  }

  if (variant === 'inline') {
    return (
      <div className={`bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-md p-4 ${className}`}>
        {disclaimerContent}
      </div>
    );
  }

  // Default banner variant
  return (
    <div className={`bg-amber-50 dark:bg-amber-900/20 border-b border-amber-200 dark:border-amber-800 px-4 py-3 ${className}`}>
      {disclaimerContent}
    </div>
  );
};

export const PrivacyNotice: React.FC<{ className?: string }> = ({ className = '' }) => (
  <div className={`bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-md p-4 ${className}`}>
    <div className="flex items-start gap-3">
      <Shield className="h-5 w-5 text-blue-500 flex-shrink-0 mt-0.5" />
      <div className="text-sm">
        <p className="font-medium text-gray-900 dark:text-gray-100 mb-1">
          Privacy & Data Protection
        </p>
        <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
          Your patent data and analysis results are processed securely. We implement industry-standard encryption, 
          access controls, and data protection measures. Analysis data is retained according to your workspace settings 
          and can be deleted upon request.
        </p>
      </div>
    </div>
  </div>
);

export const UsageGuidelines: React.FC<{ className?: string }> = ({ className = '' }) => (
  <div className={`bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-md p-4 ${className}`}>
    <div className="flex items-start gap-3">
      <Info className="h-5 w-5 text-green-500 flex-shrink-0 mt-0.5" />
      <div className="text-sm">
        <p className="font-medium text-gray-900 dark:text-gray-100 mb-1">
          Usage Guidelines
        </p>
        <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
          This tool is designed for patent research and analysis. Use responsibly and in compliance with applicable 
          laws and regulations. Do not use for unauthorized access to confidential information or to circumvent 
          intellectual property protections.
        </p>
      </div>
    </div>
  </div>
);

export const ExportDisclaimer: React.FC<{ className?: string }> = ({ className = '' }) => (
  <div className={`bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-md p-4 ${className}`}>
    <div className="flex items-start gap-3">
      <AlertTriangle className="h-5 w-5 text-red-500 flex-shrink-0 mt-0.5" />
      <div className="text-sm">
        <p className="font-medium text-gray-900 dark:text-gray-100 mb-1">
          Export & Distribution Notice
        </p>
        <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
          Exported reports and charts contain AI-generated analysis and must include this disclaimer when shared. 
          Do not distribute without proper attribution and legal review. The analysis is not a substitute for 
          professional legal counsel.
        </p>
      </div>
    </div>
  </div>
);

export const ComprehensiveDisclaimer: React.FC<{ className?: string }> = ({ className = '' }) => (
  <div className={`space-y-4 ${className}`}>
    <LegalDisclaimer variant="inline" />
    <PrivacyNotice />
    <UsageGuidelines />
    <ExportDisclaimer />
  </div>
);

export default LegalDisclaimer;
